### ISSUE TITLE
Atomics with_mut doesn't match std

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/loom#113]
In 0.3, the `Atomic*` types lost the `get_mut()` methods, and replaced them with `with_mut()`. A problem now is that the atomics from `std` don't have `with_mut()`, and the types from `loom` don't have `get_mut()`.

What's recommended way to use them?

**Comment by carllerche** [comment]
Define a wrapper: https://github.com/tokio-rs/tokio/blob/master/tokio/src/loom/std/atomic_u32.rs

The problem is `get_mut` was unable to correctly validate usage for the same reason as `UnsafeCell`.

It would be nice to either provide a crate (`loom-types` or something) that provides all the wrappers for you. Or, at least, a reference file you can copy / paste :shrug:

**Comment by seanmonstar** [comment]
I ended up adding a `trait AtomicMut` to implement when not running loom.
