### ISSUE TITLE
coredump with illegal hardware instruction

### ISSUE THREAD

**Issue by Sherlock-Holo** [tokio-rs/loom#115]
I try to use loom to check my [project](https://github.com/Sherlock-Holo/atomic_value)

When I run `cargo test --features=concurrent-test --test test`, it report

> ```
>    Compiling atomic_value v0.1.0 (/home/sherlock/git/atomic_value)
>     Finished test [unoptimized + debuginfo] target(s) in 0.57s
>      Running target/debug/deps/test-6a9029d909e56a54
> 
> running 1 test
> thread panicked while panicking. aborting.
> error: test failed, to rerun pass '--test test'
> 
> Caused by:
>   process didn't exit successfully: `/home/sherlock/git/atomic_value/target/debug/deps/test-6a9029d909e56a54` (signal: 4, SIGILL: illegal instruction)
> ```

Is there anything I write wrong? If have, could anyone help me to fix it?

**Comment by hawkw** [comment]
This is probably due to a double panic. If a panic occurs while a thread is already unwinding, a `ud2` instruction (on x86) is executed, causing the process to be killed with a SIGILL. 

Typically (but not always) double panics under `loom` occur when a test fails, due to an assertion in the test, a panic in the code under test, or `loom` detecting a model violation. In some cases, when a test panics, cleaning up the loom state for that test will destroy a `scoped_thread_local` that has already been destroyed, resulting in a second panic. 

We'd like to fix this so that `loom` tests fail with more useful diagnostics. In the meantime, you can run your test with `-- --test-threads=1 --nocapture` and the `RUST_BACKTRACE=1` env var. Then, the panics will still be printed out before your test executable is killed.

Alternatively, double panics can be caused by panics in `Drop` implementations in the code under test. In this case, you can fix it by ensuring that all `Drop` implementations in your code will never panic. To find where the panic occurred, the flags I mentioned above are useful in this case as well.

**Comment by Sherlock-Holo** [comment]
the log is https://fars.ee/kVSp/
I found something

> ```
>   27: atomic_value::AtomicValue<T>::load
>              at ./src/lib.rs:31
>   28: test::concurrent_store::{{closure}}::{{closure}}::{{closure}}
>              at tests/test.rs:17
> ```

in [./src/lib.rs:31](https://github.com/Sherlock-Holo/atomic_value/blob/master/src/lib.rs#L31) that is
```rust
while self.using.compare_and_swap(false, true, Ordering::AcqRel) {}
```

I read [std doc](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html#method.compare_and_swap) the AtomicBoll allow use `AcqRel` in `compare_and_swap`.

The normal unit test that uses std `AtomicBool` runs well. Do I use loom `AtomicBool` not right?

**Comment by hawkw** [comment]
The panic message you posted is:
```
thread 'main' panicked at 'Model exeeded maximum number of branches. This is often caused by an algorithm requiring the processor to make progress, e.g. spin locks.', /home/sherlock/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/loom-0.3.0/src/rt/path.rs:199:13
stack backtrace:
```

This means that your code has branched more than 1000 times (the default maximum number of branches that loom will take) before a thread was yielded or preempted. Does your code involve spin locks or other tight loops? This error may also indicate that you've entered an infinite loop. 

You can increase the maximum number of branches with the environment variable `LOOM_MAX_BRANCHES`. You might want to try increasing the maximum number of branches significantly and rerunning your test.

**Comment by Sherlock-Holo** [comment]
Oh you found it! I miss use `spin_loop_hint()`

After use this function, the test works well now. Thanks for your help.

**Comment by Sherlock-Holo** [comment]
Consider the problem solved, this issue can be closed now :)

**Comment by cmnord** [comment]
Hello, I am also having this issue with my own lock implementation. I put `loom::sync::atomic::spin_loop_hint()` in the body of the spin loop, but I still get the error `Model exeeded maximum number of branches. This is often caused by an algorithm requiring the processor to make progress, e.g. spin locks.`.

Is adding `spin_loop_hint` supposed to prevent this panic?
