### ISSUE TITLE
Potential memory leak in `loom::thread::spawn`

### ISSUE THREAD

**Issue by ryota2357** [tokio-rs/loom#369]
First, thank you for your work on loom, I could detect incorrect atomic control implementations with it!

It appears that `loom::thread::spawn` might introduce a memory leak. Using the [dhat](https://crates.io/crates/dhat) crate, I observed that `curr_blocks` and `curr_bytes` are non-zero after running a minimal test case. In contrast, using `std::thread::spawn` in the same test case does not exhibit this behavior. Below are the details.

## Steps to Reproduce

1. Prepare the following two files.

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "loom-leak"
version = "0.1.0"
edition = "2021"

[dependencies]
loom = "=0.7.2"
dhat = "=0.3.3"
```
</details>

<details>
<summary>src/lib.rs</summary>

```rust
#![cfg(test)]

#[global_allocator]
static ALLOC: dhat::Alloc = dhat::Alloc;

fn test_target() {
    loom::thread::spawn(|| {}).join().unwrap();
    // std::thread::spawn(|| {}).join().unwrap();
}

#[test]
fn run() {
    loom::model(|| {
        let _profiler = dhat::Profiler::builder().testing().build();
        test_target();
        let stats = dhat::HeapStats::get();
        dbg!(stats);
    })
}
```
</details>

2. Run `cargo test --release -- --nocapture`. (or `cargo test -- --nocapture`, it produce same results). You can get the following output:

```
running 1 test
[src/lib.rs:17:9] stats = HeapStats {
    total_blocks: 8,
    total_bytes: 484,
    curr_blocks: 1,
    curr_bytes: 108,
    max_blocks: 7,
    max_bytes: 356,
}
test run ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

3. To compare with `std::thread::spawn`, update src/lib.rs. Comment out `loom::thread...`, and comment in `std::thread...`.

4. Run `cargo test --release -- --nocapture`. (or `cargo test -- --nocapture`, it produce same results). You can get the following output:

```
running 1 test
[src/lib.rs:17:9] stats = HeapStats {
    total_blocks: 4,
    total_bytes: 152,
    curr_blocks: 0,
    curr_bytes: 0,
    max_blocks: 4,
    max_bytes: 152,
}
test run ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

## Expected Behavior

`loom::thread` should not leave unfreed memory blocks after completion, similar to `std::thread`.

## Environment

- cargo 1.83.0 (5ffbef321 2024-10-29)
- rustc 1.83.0 (90b35a623 2024-11-26)
- macOS 15.1.1
- Apple M1 Pro

---

Please let me know if there is any additional information or testing I can provide.
Also, I apologize if this is a problem on the dhat side.

**Comment by ryota2357** [comment]
When testing with `loom::thread::spawn`, you can get `dhat-heap.json` file by:

```rust
let stats = dhat::HeapStats::get();
dhat::assert_eq!(stats.curr_blocks, 0);
```

**Comment by mox692** [comment]
During the execution, loom allocates additional objects to track the program execution, so I suspect dhat caught these internal objects.
It's a bit unfortunate, but I believe these allocations wouldn't leak across `loom::model` or even between iterations.

**Comment by hawkw** [comment]
Yeah, Loom uses a global arena to store internal data related to the objects it simulates (such as threads). If memory serves, this lives in a `static`, so memory profiling tools such as `dhat` will see this as an allocation that's never freed. However, the arena should be reused across subsequent iterations of a model, so you shouldn't see too much of an increase in memory use over time when running Loom tests.

With that said, if you're seeing processes running Loom tests use rapidly increasing amounts of memory, or getting OOMkilled, that could be a bug that's worth investigating even if the leaks reported by `dhat` are a red herring. 

One potential culprit I've encountered in the past is actually Rust `libtest`'s output capturing. If your code under test prints stuff to stdout or stderr while it's running, libtest will capture that output and buffer it so that it can be printed only if the test fails. Because Loom must rerun the same tests a (potentially very large) number of times to simulate each potential interleaving of events permitted by the memory model, the amount of stdout/stderr buffered for that test will often grow over time quite substantially. If your test processes are getting OOMkilled because of this, you may want to try running your Loom tests with the arguments `--test-threads=1 --nocapture`, so that libtest doesn't capture stdout/stderr and instead prints it to the terminal immediately. Passing `--test-threads=1` ensures that only one of your tests is run at a time, so that the output from multiple tests doesn't get interleaved into a big pile of nonsense.

**Comment by ryota2357** [comment]
> If memory serves, this lives in a `static` ...

I see, thank you for explaining the mechanism of loom.

> Loom tests use rapidly increasing amounts of memory, or getting OOMkilled...

I’ve never encountered these problems before.
In my current developing program, the issue caused by atomic operation mistakes could lead to memory leaks. That’s why I was particularly curious about the small curr_blocks value in this case.

---

I modified the minimal test case as follows:

```rust
    let _profiler = dhat::Profiler::builder().testing().build();
    {
        loom::model(|| {
            test_target();
        });
    }
    let stats = dhat::HeapStats::get();
    dbg!(stats);
```

With this change, dhat reports the same amount of leaks regardless of whether `std::thread` or `loom::thread` is used.
(Run with `cargo test --release -- --test-threads=1 --nocapture`)

```
# With std::thread
test run ... [src/lib.rs:20:5] stats = HeapStats {
    total_blocks: 22,
    total_bytes: 741081,
    curr_blocks: 7,
    curr_bytes: 3056,
    max_blocks: 18,
    max_bytes: 740992,
}

# With loom::thread
test run ... [src/lib.rs:20:5] stats = HeapStats {
    total_blocks: 28,
    total_bytes: 741470,
    curr_blocks: 7,
    curr_bytes: 3056,
    max_blocks: 21,
    max_bytes: 741196,
}
```

As you mentioned, this seems to be a limitation or characteristic of dhat (the memory profiler), as it treats `static` allocations as unfreed memory.

> One potential culprit I’ve encountered in the past is actually Rust libtest’s output capturing. ...

I wasn’t aware of that.
As you pointed out, when I ran the modified minimal test case without --test-threads=1, I observed an increase in `curr_blocks` and `curr_bytes`.

---

Thank you for your quick response and helpful advice!

This issue is not a bug or problem with loom itself, so I will close it.
